### ISSUE TITLE
NavigationBar Tile Issue

### ISSUE THREAD

**Issue by micheleberrettis1** [DotOS/android_packages_apps_DotExtras#14]
The NavBar tile has only the tweaks section that sends you to the buttons settings of lineageOS, just change the name of the tile in buttons&navbar and you are done... easier to find as in the buttons panel there is the only option for the volume keys...

**Comment by ganeshi4u** [comment]
eh? that's not how it works and having a separate section for navigation bar tweaks is more preferable than moving it to the Buttons section, if it is that what you mean.

**Comment by micheleberrettis1** [comment]
contact you in telegram to let you understand.
