### ISSUE TITLE
FAILED AT LINE 32 OF traffic.xml 

### ISSUE THREAD

**Issue by arkaroy14** [DotOS/android_packages_apps_DotExtras#3]
After editing all these got error in line 32 of traffic.xml..System only identify max but not identify min and units of CustomSeekBarPreference.java
Error attached here https://hastebin.com/keceveseku.rb

**Comment by Anandnv** [comment]
Coz of wrong detection from custom seekbar
Change Settings_* to Android  it will fix that

**Comment by mohancm** [comment]
hmm....
